// GENERATED by scripts/gen_products_data.py — do not edit by hand.
// Source of truth: <lang>/products/<slug>.md front matter
// (title / summary / productImage) + _data/productOrder.json for order.
module.exports = {
  "en": [
    {
      "id": "strong-grooving-wheels",
      "name": "High-strength grooving grinding wheel",
      "summary": "SAP high-strength grooving grinding wheel combines the advantages of metal grinding wheel and ceramic grinding wheel, featuring high self-sharpening, high sharpness, high shape retention, easy dressing and other advantages, particularly suitable for high-efficiency processing of cemented carbide, high-speed steel and cermet rotary tools and blades.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Semiconductor LED chip back thinning grinding wheel disc",
      "summary": "Used for precision grinding of ultra-hard semiconductor materials such as sapphire and SiC, such as back thinning of LED sapphire substrate wafers, SiC substrate wafers, GaAs substrate wafers, and other grinding and thinning; good self-sharpening, high form retention, easy dressing, low scratch rate, low breakage rate.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "powder metallurgy high-speed steel",
      "summary": "SAP series powder metallurgy high-speed steel is mainly used in the high-end tool and mold industry, replacing imported materials; it can prepare complex workpieces with near-net shape, has low impurity content, and covers multiple series such as tool steel, high-chromium stainless high-speed steel, titanium-nickel high-speed steel, etc.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo Super Alloy Heat Spreader",
      "summary": "Used for 3D glass hot bending molds and semiconductor thermal management, uniform heating, high planarity, long service life, supports non-standard custom sizes.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiC wafer thinning wheel",
      "summary": "Diamond grinding wheel using a single homogeneous cermet (intermetallic compound) bond; rough grinding 2000# high feed efficient, finish grinding 30000# finish 2nm or less, greatly reduces subsequent polishing volume, improves yield.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Solar silicon ingot squaring and chamfering grinding wheel",
      "summary": "Removing saw marks and surface damage layers after squaring to achieve flatness and parallelism; removing coarse grinding marks to achieve corresponding surface finish; long service life, high surface finish, and good stability.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Resin grinding wheel for five-axis grinder",
      "summary": "Using resin as the bond, equipped with diamond or CBN superhard abrasive, adapted to the high-precision motion of five-axis grinders, specifically for precision grinding of complex contour surfaces of difficult-to-machine materials such as cemented carbide and high-speed steel, it is the core consumable in CNC tool manufacturing.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Steel-bonded cemented carbide",
      "summary": "Targets tooling and harsh wear-resistant components — in the annealed state it can be directly machined by turning, milling, and drilling; it supports forging and welding, and forming can be completed without special equipment; after quench hardening, HRC 60–70, wear resistance is close to high-cobalt cemented carbide, toughness is far superior to ordinary cemented carbide, and full lifecycle cost is far lower than conventional alloy die steel.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "zh": [
    {
      "id": "strong-grooving-wheels",
      "name": "强力开槽砂轮",
      "summary": "SAP 强力开槽砂轮兼具金属砂轮和陶瓷砂轮的优势，具有高自锐性、高锋利度、高保型性、易修整等优点，特别适合硬质合金、高速钢及金属陶瓷回转体刀具及刀片的高效率加工。",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "半导体LED芯片背减薄砂轮盘",
      "summary": "应用于蓝宝石、SiC 等超硬半导体材料的精密磨削，如 LED 蓝宝石衬底片背减薄、SiC 衬底片、GaAs 衬底片等磨削减薄；自锐性好、保型性高、易修型、低划伤率、低破片率。",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "粉末冶金高速钢",
      "summary": "SAP 系列粉末冶金高速钢主要用于高端工模具行业，替代进口材料；可近净成型制备复杂工件，杂质含量低，并涵盖模具钢、高铬不锈高速钢、钛镍高速钢等多个系列。",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo 超合金均热板",
      "summary": "用于 3D 玻璃热弯模具与半导体热管理，加热均匀、平面度高、使用寿命长，支持非标定制尺寸。",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "碳化硅晶圆减薄砂轮",
      "summary": "采用单一均质金属陶瓷（金属间化合物）结合剂的金刚石砂轮；粗磨 2000# 大进给高效，精磨 30000# 光洁度 2nm 以下，大大减少后道抛光量、提升良率。",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "光伏硅锭磨方倒角砂轮",
      "summary": "去除开方后锯痕及表面损伤层，达到平坦度与平行度；去除粗磨痕迹达到相应光洁度；使用寿命长、表面光洁度高、稳定性好。",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "五轴磨床用树脂砂轮",
      "summary": "以树脂为结合剂、配金刚石或 CBN 超硬磨料，适配五轴磨床高精度运动，专用于硬质合金、高速钢等难加工材料的复杂型面精密磨削，是数控刀具制造的核心耗材。",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "钢结硬质合金",
      "summary": "面向刀具与苛刻耐磨件——退火态可直接车、铣、钻加工，支持锻造与焊接，无需特殊设备即可成型；淬硬后 HRC 60–70，耐磨性接近高钴硬质合金、韧性远优于普通硬质合金，全生命周期成本远低于常规合金模具钢。",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "zh-tw": [
    {
      "id": "strong-grooving-wheels",
      "name": "強力開槽砂輪",
      "summary": "SAP 強力開槽砂輪兼具金屬砂輪和陶瓷砂輪的優勢，具有高自銳性、高鋒利度、高保型性、易修整等優點，特別適合硬質合金、高速鋼及金屬陶瓷回轉體刀具及刀片的高效率加工。",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "半導體LED晶片背減薄砂輪盤",
      "summary": "應用於藍寶石、SiC 等超硬半導體材料的精密磨削，如 LED 藍寶石襯底片背減薄、SiC 襯底片、GaAs 襯底片等磨削減薄；自銳性好、保型性高、易修型、低劃傷率、低破片率。",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "粉末冶金高速鋼",
      "summary": "SAP 系列粉末冶金高速鋼主要用於高端工模具行業，替代進口材料；可近淨成型製備複雜工件，雜質含量低，並涵蓋模具鋼、高鉻不銹高速鋼、鈦鎳高速鋼等多個系列。",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo 超合金均熱板",
      "summary": "用於 3D 玻璃熱彎模具與半導體熱管理，加熱均勻、平面度高、使用壽命長，支持非標定制尺寸。",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "碳化矽晶圓減薄砂輪",
      "summary": "採用單一均質金屬陶瓷（金屬間化合物）結合劑的鑽石砂輪；粗磨 2000# 大進給高效，精磨 30000# 光潔度 2nm 以下，大大減少後道拋光量、提升良率。",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "光伏矽錠磨方倒角砂輪",
      "summary": "去除開方後鋸痕及表面損傷層，達到平坦度與平行度；去除粗磨痕跡達到相應光潔度；使用壽命長、表面光潔度高、穩定性好。",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "五軸磨床用樹脂砂輪",
      "summary": "以樹脂為結合劑、配鑽石或 CBN 超硬磨料，適配五軸磨床高精度運動，專用於硬質合金、高速鋼等難加工材料的複雜型面精密磨削，是數控刀具製造的核心耗材。",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "鋼結硬質合金",
      "summary": "面向刀具與苛耐磨件——退火態可直接車、銑、鑽加工，支持鍛造與焊接，無需特殊設備即可成型；淬硬後 HRC 60–70，耐磨性接近高鎳硬質合金、韌性遠優於普通硬質合金，全生命週期成本遠低於常規合金模具鋼。",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "de": [
    {
      "id": "strong-grooving-wheels",
      "name": "Starkes Schlitzschleifrad",
      "summary": "Das SAP starke Schlitzschleifrad kombiniert die Vorteile von Metall- und Keramik-Schleifrad und bietet hohe Selbstscharfheit, hohe Schärfe, hohe Formtreue, leichtes Schruppen und andere Vorteile und eignet sich besonders für die effiziente Bearbeitung von Hartmetall, Schnellstahl und keramischen Metall-Rotationsschneidwerkzeugen und -klingen.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Halbleiter-LED-Chip-Rückendünnschliff-Schleifscheibe",
      "summary": "Vereinfachung von Präzisschleifen von superharten Halbleitermaterialien wie Saphir, SiC, wie z.B. das Rückendünnschleifen von LED-Saphir-Substratplatinen, SiC-Substratplatinen, GaAs-Substratplatinen und andere Schleif- und Dünnschliffarbeiten; gute Selbstschärfung, hohe Formbeständigkeit, leichtes Nachschleifen, niedrige Kratzerate, niedrige Bruchrate.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "Pulvermetallurgie-Schnellstahl",
      "summary": "SAP-Serie Pulvermetallurgie-Schnellstahl wird hauptsächlich in der High-End-Werkzeug- und Schablonenindustrie verwendet, um importierte Materialien zu ersetzen; komplexe Werkstücke können nahe der Nettoform hergestellt werden, der Anteil an Verunreinigungen ist gering, und es umfasst mehrere Serien wie Stanzstahl, hochchromhaltiger rostfreier Schnellstahl, Titan-Nickel-Schnellstahl usw.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo Superlegierungswärmeleiter",
      "summary": "Für 3D-Glas-Hot-Bending-Formen und Halbleiter-Thermalmanagement, gleichmäßige Erwärmung, hohe Planität, lange Lebensdauer, unterstützt nicht-standardisierte kundenspezifische Größen.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiC-Wafer-Dünnschliff",
      "summary": "Diamantscheibe mit einhüligem Keramikmetallbindematerial (intermetallisches Verbund); Grobschliff 2000# hohe Fressrate effizient, Feinschliff 30000# Oberfläche 2nm oder weniger, reduziert die spätere Poliermenge erheblich, steigert den Ausbeute.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Grindrad für das Quadratischschleifen und Fasen von PV-Siliziumingots",
      "summary": "Entfernung von Sägespuren und Schichtenschädigungen nach dem Quadratisieren, um Ebenheit und Parallelität zu erreichen; Entfernung von Grobschliffspuren, um die entsprechende Oberflächengüte zu erreichen; lange Lebensdauer, hohe Oberflächengüte und gute Stabilität.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Kunstharzschleifscheibe für Fünf-Achs-Schleifmaschinen",
      "summary": "Verwendet Kunstharz als Bindung, kombiniert mit Diamant oder CBN-Überschliffwerkzeug, angepasst an die Hochpräzisionsbewegung von Fünf-Achs-Schleifmaschinen, speziell für das präzise Schleifen komplexer Konturen von schwer zu bearbeitenden Materialien wie Hartmetall und Schnellstahl, ist das Kernverbrauchs- material in der CNC-Werkzeugherstellung.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Stahlgebundener Hartmetall",
      "summary": "Zielt auf Werkzeuge und anspruchsvolle Verschleißteile ab — im gelöschten Zustand kann er direkt gedreht, gefräst und gebohrt werden; er unterstützt Schmieden und Schweißen, und Formgebung kann ohne Spezialausrüstung abgeschlossen werden; nach Härtung HRC 60–70, Verschleißfestigkeit ähnlich wie bei hochcobaltigem Hartmetall, Zähigkeit weit überlegen gegenüber normalem Hartmetall, Lebenszykluskosten weit niedriger als konventioneller legierter Werkzeugstahl.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "ja": [
    {
      "id": "strong-grooving-wheels",
      "name": "強力スロット研削砥石",
      "summary": "SAP強力スロット研削砥石は金属砥石とセラミック砥石の利点を兼ね備え、高い自己研削性、高い鋭利度、高い形保持性、修正の容易さなどの利点をもち、超硬合金、高速鋼およびセラミック金属回転体工具とブレードの効率的な加工に特に適しています。",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "半導体LEDチップ裏面研削砥石盤",
      "summary": "サファイア、SiCなどの超硬半導体材料の精密研削に使用され、例えばLEDサファイア基板の裏面研削、SiC基板、GaAs基板などの研削薄化；自己研削性がよく、型崩れ防止性が高く、研削調整が容易で、スクラッチ率が低く、破片率が低い。",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "粉末冶金高速度鋼",
      "summary": "SAPシリーズ粉末冶金高速度鋼は、主にハイエンド工具型業界で使用され、輸入材料を代替します；複雑なワークを近净形態で製造でき、不純物含量が低く、金型鋼、高クロムステンレス高速度鋼、チタンニッケル高速度鋼等多个系列をカバーします。",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo スーパー合金放熱板",
      "summary": "3Dガラス熱曲げ型と半導体熱管理に使用され、加熱が均一で、平面度が高く、使用寿命が長く、非標準のカスタムサイズに対応。",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiCウェーハ研削",
      "summary": "単一の均一なセラミックメタルバインド（金属間化合物）結合剤を持つダイヤモンド砥石；荒研ぎ 2000# 大きな送り量で高効率、仕上げ研ぎ 30000# 光沢度 2nm 以下、後工程の研磨量を大幅に削減し、歩留まりを向上。",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "太陽光シリコンインゴット方形研削・角取り砥石",
      "summary": "方形化後ののこ残りおよび表面損傷層を除去し、平面度と平行度を達成；粗研ぎ痕を除去し、対応する表面粗さを達成；使用寿命が長く、表面粗さが低く、安定性が良い。",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "5軸研削盤用樹脂砥石",
      "summary": "樹脂を結合剤とし、ダイヤモンドまたはCBN超硬研削材を組み合わせ、5軸研削盤の高精度運動に適応、硬质合金、高速鋼などの加工困難な素材の複雑な形状面の精密研削専用、NC工作物製造のコア消費品です。",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "鋼結合超硬合金",
      "summary": "工具および苛酷な耐摩耗部材をターゲットとしています——焼ならし状態では直接旋削、フライス、ドリリング加工が可能であり、鍛造と溶接をサポートし、特殊設備なしで成形が可能です；油焼入れ後HRC 60–70、耐摩耗性は高コバルト超硬合金に近く、靭性は通常の超硬合金をはるかに超え、全ライフサイクルコストは常規の合金金型鋼よりはるかに低いです。",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "ko": [
    {
      "id": "strong-grooving-wheels",
      "name": "강력한 경선 연삭 휠",
      "summary": "SAP 강력한 경선 연삭 휠은 금속 연삭 휠과 세라믹 연삭 휠의 장점을 겸비하여 높은 자체 연마성, 높은 예리도, 높은 형상 보존성, 손쉬운 교정 등의 장점을 갖추고 있으며, 탄화강, 고속강 및 서멧 회전체 공구 및 블레이드의 효율적인 가공에 특히 적합합니다.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "반도체 LED 칩 뒷면 연삭 돌반",
      "summary": "사파이어, SiC 등의 초경 반도체 소재의 정밀 연삭에 적용되며, 예를 들어 LED 사파이어 기판 뒷면 연삭, SiC 기판, GaAs 기판 등의 연삭 및 파두; 자가 연마성이 좋고, 형상 유지성이 높으며, 연삭 조정이 쉽고, 스크래치율이 낮고, 파편화율이 낮습니다.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "분말야금 고속강",
      "summary": "SAP 시리즈 분말야금 고속강은 주로 고급 금형 및 공구 산업에 사용되며 수입 재료를 대체합니다; 복잡한 부품을 청정가공으로 제조할 수 있으며 불순물 함량이 낮고, 금형강, 고크롬 스테인리스 고속강, 티타늄-니켈 고속강 등 여러 시리즈를 포괄합니다.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo 초합금 히트 스프리더",
      "summary": "3D 유리 열 성형 금형과 반도체 열 관리에 사용되며, 균일한 가열, 높은 평탄도, 긴 사용 수명, 비표준 맞춤 크기 지원.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiC 웨이퍼 씬닝",
      "summary": "단일 균질 서멧 결합제(금속 간 화합물) 결합제를 사용하는 다이아몬드 휠; 거친 연삭 2000# 큰 절송量 고 효율, 마무리 연삭 30000# 광택도 2nm 이하, 후공정 연마량을 대폭 줄이고 수율을 높입니다.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "태양광 실리콘 잉고트 정사각형 연마 및 모따기 휠",
      "summary": "사각화 후 톱자국 및 표면 손상층을 제거하여 평탄도와 평행을 달성；굵은 연마 흔적을 제거하여 적절한 표면 거칠기를 달성；수명 길음, 높은 표면 거칠기, 좋은 안정성.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "5축 연삭기용 수지 연삭 휠",
      "summary": "수지를 결합제로 사용하고 다이아몬드 또는 CBN 초경 연삭재를 조합하여, 5축 연삭기 고밀도 운동에 맞춰져, 탄화강, 고속강 등 가공이 어려운 소재의 복잡한 형상 정밀 연삭 전용이며, CNC 공정 제조의 핵심 소모품입니다.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "강결 탄화강",
      "summary": "공구와 가혹한 마모 저항 부품을 대상으로 합니다——소둔 상태에서 직접 선반, 밀링, 드릴링 가공이 가능하며, 대조와 용접을 지원하며 특수 장비 없이 성형이 가능합니다; 담금질 후 HRC 60–70, 마모 저항성은 고코발트 탄화강에 근접하고, 인성은 일반 탄화강보다 훨씬 우수하며, 전수명주기 비용은 일반 합금 금형강보다 훨씬 낮습니다.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "ru": [
    {
      "id": "strong-grooving-wheels",
      "name": "Мощный проточный абразивный круг",
      "summary": "SAP мощный проточный абразивный круг сочетает преимущества металлических и керамических абразивных кругов, обладая высокой самозатачиваемостью, высокой остротой, высокой сохранностью формы, легкостью правки и другими преимуществами, особенно подходящий для высокоэффективной обработки твердосплава, быстрорежущей стали и керамико-металлических вращающихся режущих инструментов и пластин.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Круг для тонкого шлифования тыльной стороны чипов светодиодов для полупроводников",
      "summary": "Применяется для точного шлифования сверхтвердых полупроводниковых материалов, таких как сапфир, SiC, включая тонкое шлифование тыльной стороны подложек из сапфира для светодиодов, подложек из SiC, подложек из GaAs и другие операции шлифования и утоньшения; хорошая самоостригаемость, высокая сохранность формы, легкость правки, низкий уровень царапин, низкий уровень повреждения пластин.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "порошковая быстрорежущая сталь",
      "summary": "Порошковая быстрорежущая сталь серии SAP в основном используется в высокотехнологичной отрасли инструмента и оснастки, заменяя импортные материалы; возможно изготовление сложных деталей с почти чистой геометрией, низкое содержание примесей, и охватывает несколько серий, таких как инструментальная сталь, высокохромовая нержавеющая быстрорежущая сталь, титано-никелевая быстрорежущая сталь и т.д.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo Суперсплав радиатор",
      "summary": "Используется для 3D-стекла термических гибочных форм и теплового управления полупроводников, равномерный нагрев, высокая плоскостность, долгий срок службы, поддерживает нестандартные размеры по индивидуальному заказу.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiC пластины",
      "summary": "Алмазный круг с однородной керамико-металлической связкой (металлоидное соединение); чистовое обтачивание 2000# с крупным шагом для высокой эффективности, финишное обтачивание 30000# с шероховатостью 2 нм и менее, значительно снижает последующую полировку, повышает выход годного.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Круг для шлифования и фаски фотоэлектрических кремниевых заготовок",
      "summary": "Удаление следов пиления и поверхностных слоёв повреждения после квадрования для достижения плоскостности и параллельности; удаление следов грубого шлифования для достижения соответствующей гладкости; длительный срок службы, высокая гладкость поверхности, хорошая стабильность.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Абразивный круг из смолы для пятикоординатных станков",
      "summary": "С использованием смолы в качестве связки, в сочетании с алмазом или CBN сверхтвердым абразивным материалом, адаптированным к высокоточному движению пятикоординатных станков, специально для точного шлифования сложных поверхностей труднообрабатываемых материалов, таких как твердосплав и быстрорежущая сталь, является основным расходом для производства CNC-инструментов.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Стальносвязанный твёрдосплав",
      "summary": "Предназначен для режущего инструмента и деталей, работающих в жёстких условиях износостойкости — в отожжённом состоянии может напрямую обрабатываться токарной, фрезерной и сверлильной обработкой; поддерживает ковку и сварку, формовка возможна без специального оборудования; после закалки HRC 60–70, износостойкость близка к высококобальтовому твёрдосплаву, вязкость значительно превосходит обычный твёрдосплав, совокупные затраты на весь жизненный цикл значительно ниже, чем у обычного легированного штамповой стали.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "es": [
    {
      "id": "strong-grooving-wheels",
      "name": "Rueda de laminado de alta potencia",
      "summary": "La rueda de laminado de alta potencia SAP combina las ventajas de las ruedas de laminado de metal y cerámica, ofreciendo alta autorrenovación, alta agudeza, alta retención de forma, facilidad de rectificado y otras ventajas, y es particularmente adecuada para el procesamiento de alta eficiencia de herramientas de rotación de carburo, acero rápido y cermet y hojas.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Disco de rectificado de adelgazamiento posterior de chips LED de semiconductores",
      "summary": "Se aplica al rectificado de precisión de materiales semiconductores ultra-duros como zafiro, SiC, como el adelgazamiento posterior de sustratos de zafiro para LED, sustratos de SiC, sustratos de GaAs y otros rectificados de adelgazamiento; buena autoafilado, alta retención de forma, fácil refilado, baja tasa de arañado, baja tasa de rotura.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "acero rápido de metalurgia de polvos",
      "summary": "El acero rápido de metalurgia de polvos de la serie SAP se utiliza principalmente en la industria de herramientas y moldes de gama alta, sustituyendo los materiales importados; permite preparar piezas complejas en forma casi neta, tiene bajo contenido de impurezas y cubre múltiples series como acero de molde, acero rápido inoxidable de alto cromo, acero rápido de titanio y níquel, entre otras.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "Disipador de calor de superaleación TiNiCo",
      "summary": "Se utiliza para moldes de doblado térmico de vidrio 3D y gestión térmica de semiconductores, calentamiento uniforme, alta planaridad, larga vida útil, admite tamaños personalizados no estándar.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "rueda de adelgazado de obleas SiC",
      "summary": "Rueda de diamante con aglutinante cermet (compuesto intermetálico) homogéneo y único; desbaste 2000# alta avance eficiente, acabado 30000# acabado 2nm o menos, reduce significativamente el volumen de pulido posterior, mejora la tasa de rendimiento.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Rueda de rectificado para squaring y chaflán de lingotes de silicio fotovoltaico",
      "summary": "Eliminar las marcas de sierra y capas de daño superficial tras el squaring para lograr planitud y paralelismo; eliminar las marcas de rectificado grueso para lograr la limpieza superficial correspondiente; larga vida útil, alta limpieza superficial y buena estabilidad.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Rueda de molde de resina para rectificadoras de cinco ejes",
      "summary": "Con resina como ligante, combinado con material abrasivo superduro de diamante o CBN, adaptado al movimiento de alta precisión de las rectificadoras de cinco ejes, dedicado al rectificado de precisión de superficies complejas de materiales de difícil mecanizado como cemented carbide y high-speed steel, es el material de consumo central en la fabricación de herramientas CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Carburo aglutinado con acero",
      "summary": "Dirigido a herramientas y piezas resistentes al desgaste en condiciones exigentes: en estado recocido puede ser mecanizado directamente por torneado, fresado y taladrado; soporta forja y soldadura, y la conformación puede completarse sin equipos especiales; tras el temple HRC 60–70, resistencia al desgaste similar al carburo de alto cobalto, tenacidad muy superior al carburo común, y coste de ciclo de vida total mucho menor que el acero de molde aleado convencional.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "pt": [
    {
      "id": "strong-grooving-wheels",
      "name": "Roda de serração de alta resistência",
      "summary": "A roda de serração de alta resistência SAP combina as vantagens de rodas metálicas e de cerâmica, apresentando alta autoafiamento, alta agudeza, alta manutenção de forma e facilidade de retratamento, sendo particularmente adequada para o processamento de alta eficiência de ferramentas de corte rotativas e lâminas de carboneto, aço rápido de metalurgia de pó e cermet.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Roda de afinação de fundo para chips LED de semicondutores",
      "summary": "Aplicada ao desbaste preciso de materiais semicondutores superduros como safiro e SiC, como o desbaste de fundo de substratos de safiro LED, substratos de SiC, substratos de GaAs, etc.; boa auto-afiamento, alta retenção de forma, fácil retificação, baixa taxa de arranhões, baixa taxa de quebra.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "aço rápido de metalurgia de pó",
      "summary": "O aço rápido de metalurgia de pó da série SAP é principalmente usado na indústria de ferramentas e moldes de alta gama, substituindo materiais importados; pode preparar peças complexas por conformação quase definitiva, com baixo teor de impurezas, e cobre várias séries, incluindo aço para moldes, aço rápido inoxidável de alto cromo, aço rápido de titânio e níquel, entre outros.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "Placa de dispersão de calor de superliga TiNiCo",
      "summary": "Usadas em moldes de dobra térmica para vidro 3D e gerenciamento térmico de semicondutores, aquecimento uniforme, alta planicidade, longa vida útil, suporta dimensões personalizadas não padrão.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "Roda de desbaste de wafer SiC",
      "summary": "Roda de diamante com aglutinante de metal cerâmico único homogêneo (compósitos intermetálicos); desbaste grosso 2000# com alta eficiência de avanço, acabamento fino 30000# com rugosidade abaixo de 2nm, reduzindo significativamente a quantidade de polimento posterior e melhorando a taxa de aproveitamento.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Roda de diamante para desbaste e chanfragem de lingotes de silício fotovoltaico",
      "summary": "Remove marcas de serra e camada de dano superficial após a quadratura, atingindo planicidade e paralelismo; remove marcas de desbaste grosseiro, atingindo brilho correspondente; longa vida útil, alto brilho superficial, boa estabilidade.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Roda de diamante de resina para retificadora de cinco eixos",
      "summary": "Com aglutinante de resina, combinado com abrasivo superduro de diamante ou CBN, adaptado ao movimento de alta precisão da retificadora de cinco eixos, especificamente para o retifica preciso de perfis complexos de materiais difíceis de trabalhar, como carboneto e aço rápido, sendo o consumível central para a fabricação de ferramentas CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Carboneto de cimento com ligante de aço",
      "summary": "Destinado a ferramentas de corte e peças com desgaste severo — no estado de recozimento pode ser usinado diretamente por torneamento, fresamento e furação, suporta forjamento e soldagem, e a formação de formas pode ser realizada sem equipamentos especiais; após a têmpera HRC 60–70, a resistência ao desgaste é próxima à do carboneto de cimento de alto teor de cobalto, a tenacidade é muito superior à do carboneto de cimento comum, o custo do ciclo de vida total é muito inferior ao do aço para molde ligado convencional.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "fr": [
    {
      "id": "strong-grooving-wheels",
      "name": "Meule de rainurage haute résistance",
      "summary": "La meule de rainurage haute résistance SAP combine les avantages des meules métalliques et céramiques, offrant une haute auto-aiguisabilité, une haute acuité, une haute rétention de forme et une facilité de dressage, étant particulièrement adaptée au traitement à haute efficacité des outils de coupe de révolution et des lames en carbure, acier rapide et céramique-métal.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Meule d'amincissement de dos pour puces LED semi-conducteurs",
      "summary": "Appliquée au meulage de précision de matériaux semi-conducteurs ultra-durs comme le saphir et le SiC, tels que l'amincissement de dos de substrats de saphir LED, de substrats SiC, de substrats GaAs, etc.; bonne auto-aiguisage, haute fidélité de forme, facile à dresser, faible taux de rayure, faible taux de casse.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "acier rapide à métallurgie des poudres",
      "summary": "L'acier rapide à métallurgie des poudres de la série SAP est principalement utilisé dans l'industrie des outils et matrices de haute qualité, remplaçant les matériaux importés ; il permet la fabrication de pièces complexes par préformation, avec une faible teneur en impuretés, et couvre plusieurs séries, y compris acier à matrices, acier rapide inoxydable à haute teneur en chrome, acier rapide au titane et au nickel, entre autres.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "Plaque de propagation de chaleur super alliage TiNiCo",
      "summary": "Utilisée pour les moules de thermoformage du verre 3D et la gestion thermique des semi-conducteurs, chauffage uniforme, haute planarité, longue durée de vie, prise en charge de dimensions personnalisées hors norme.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "Meule d'amincissement de wafer SiC",
      "summary": "Meule diamant avec liant céramique métallique unique et homogène (composé intermétallique) ; rectification grossière 2000# à grande avance et haute efficacité, finition 30000# avec rugosité inférieure à 2nm, réduisant considérablement la quantité de polissage ultérieur et améliorant le taux de rebut.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Meule diamant pour fraisage et chanfreinage de lingots de silicium photovoltaïques",
      "summary": "Enlève les marques de scie et la couche de dommages de surface après la mise en carré, atteignant la planéité et le parallélisme ; enlève les marques de fraisage grossier, atteignant la brillance correspondante ; longue durée de vie, haute brillance de surface, bonne stabilité.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Meule diamant en résine pour rectifieuse à cinq axes",
      "summary": "Avec liant résine, associé à un abrasif superdur de diamant ou CBN, adapté au mouvement de haute précision de la rectifieuse à cinq axes, spécifiquement pour le rectification précis de profils complexes de matériaux difficiles à usiner, tels que le carbure et l'acier rapide, et constitue le consommable central de la fabrication des outils CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Carbure de ciment lié au acier",
      "summary": "Destiné aux outils de coupe et aux pièces résistantes à l'usure sévères — à l'état recuit, il peut être usiné directement par tournage, fraisage et perçage, il prend en charge le forgeage et la soudure, la formation peut être réalisée sans équipements spéciaux ; après trempe HRC 60–70, la résistance à l'usure est proche de celle du carbure de ciment à haute teneur en cobalt, la ténacité est bien supérieure à celle du carbure de ciment courant, le coût du cycle de vie total est bien inférieur à celui de l'acier d'outillage allié conventionnel.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "it": [
    {
      "id": "strong-grooving-wheels",
      "name": "Mola di scanalatura ad alta resistenza",
      "summary": "La mola di scanalatura ad alta resistenza SAP combina i vantaggi delle mole metalliche e ceramiche, presentando alta autoaffilatura, alta acume, alta mantenimento della forma e facile dressaggio, ed è particolarmente adatta per la lavorazione ad alta efficienza di utensili di taglio rotativi e lame in carburo, acciaio rapido e cermet.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Mola di assottigliamento retro per chip LED a semiconduttore",
      "summary": "Applicata alla rettifica di precisione di materiali semiconduttori ultra-duri come zaffiro e SiC, ad esempio l'assottigliamento retro di substrati in zaffiro LED, substrati in SiC, substrati in GaAs, ecc.; buona auto-temperatura, alta tenutività di forma, facile ripristino, bassa percentuale di graffi, bassa percentuale di rottura.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "acciaio rapido da metallurgia delle polveri",
      "summary": "L'acciaio rapido da metallurgia delle polveri della serie SAP è principalmente utilizzato nell'industria di utensili e stampi di fascia alta, sostituendo i materiali importati; può preparare pezzi complessi mediante formatura quasi netta, con basso contenuto di impurità, e copre diverse serie, tra cui acciaio per stampi, acciaio rapido inossidabile ad alto cromo, acciaio rapido in titanio e nichel, tra gli altri.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "Piastre di dispersione del calore in superlega TiNiCo",
      "summary": "Utilizzate negli stampi per la flessione a caldo del vetro 3D e nella gestione termica dei semiconduttori, riscaldamento uniforme, elevata planarità, lunga durata, supporto per dimensioni personalizzate non standard.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "Mola di assottigliamento wafer SiC",
      "summary": "Mole per diamante con legante cermet unico omogeneo (composto intermetallico); rettifica grossa 2000# ad alta efficienza con grande avanzamento, finitura 30000# con rugosità inferiore a 2nm, riducendo significativamente la quantità di lucidatura a valle e migliorando il tasso di resa.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Mole diamant per fresatura e smusso di lingotti di silicio fotovoltaici",
      "summary": "Rimuove le tracce di sega e lo strato di danni superficiali dopo la quadratura, raggiungendo planarità e parallelismo; rimuove le tracce di fresatura grossolana, raggiungendo la lucentezza corrispondente; lunga durata, alta lucentezza superficiale, buona stabilità.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Mole in resina per rettificatrice a cinque assi",
      "summary": "Con legante resinosa, abbinata ad abrasivo superduro in diamante o CBN, adatto al movimento ad alta precisione della rettificatrice a cinque assi, specificamente per la rettifica precisa di superfici complesse di materiali difficili da lavorare, come carburo e acciaio rapido, ed è il consumabile centrale per la produzione di utensili CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Carburo cementato con lega in acciaio",
      "summary": "Destinato a utensili di taglio e parti resistenti all'usura severe — nello stato ricotto può essere lavorato direttamente su tornio, fresato e forato, supporta forgiatura e saldatura, la formazione può essere completata senza attrezzature speciali; dopo la tempra HRC 60–70, la resistenza all'usura è vicina a quella del carburo cementato ad alto tenore di cobalto, la tenacità è molto superiore a quella del carburo cementato comune, il costo del ciclo di vita totale è molto inferiore a quello dell'acciaio per stampi legato convenzionale.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "tr": [
    {
      "id": "strong-grooving-wheels",
      "name": "Yüksek dirençli oluk delme taşı",
      "summary": "SAP yüksek dirençli oluk delme taşı, metal ve seramik taşların avantajlarını birleştirir; yüksek kendiliğinden keskinleşme, yüksek keskinlik, yüksek form koruma ve kolay düzenleme gibi üstünlükler sunar ve sert metal, hızlı kesen çelik ve seramik metal döner kesme araçları ve bıçakların yüksek verimlilikle işlenmesi için özellikle uygundur.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Yarı iletken LED çipi arka inceltme taşı",
      "summary": "Yakut ve SiC gibi aşırı sert yarı iletken malzemelerin hassas taşlanmasında kullanılır; örneğin LED yakut alt tabaka arka inceltme, SiC alt tabaka, GaAs alt tabaka taşlama ve inceltme; iyi otomatik keskinleşme, yüksek form tutma, kolay taşlama, düşük çizik oranı, düşük kırılma oranı.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "toz metalurjisi yüksek hızlı çelik",
      "summary": "SAP serisi toz metalurjisi yüksek hızlı çelik, ithal malzemeleri değiştirerek yüksek segment kalıp ve takım endüstrisinde ana olarak kullanılır; düşük safsızlık içeriğine sahip olup karmaşık parçaların neredeyse net şekillendirme ile hazırlanmasına izin verir ve kalıp çeliği, yüksek kromlu paslanmaz yüksek hızlı çelik, titanyum-nikel yüksek hızlı çelik gibi birçok seriyi kapsar.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "TiNiCo süper alaşım ısı yayıcı",
      "summary": "3D cam termal büküm kalıpları ve yarı iletken termal yönetiminde kullanılır; eşit ısıtma, yüksek düzlük, uzun ömür, standart dışı özel boyutları destekler.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "SiC wafer inceltme",
      "summary": "Tek tip homojen metal seramik (aralık metal bileşimi) bağlayıcılı elmas taş; kaba talaş 2000# yüksek verimli yüksek ilerleme, zımparalamada 30000# pürüzsüzlüğü 2nm altı, sonraki aşamadaki cilalama miktarını önemli ölçüde azaltır, verimi artırır.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Fotovoltaik silikon ingot dikdörtgenleme ve pahalamada elmas taş",
      "summary": "Kare kesim sonrası testere izlerini ve yüzey hasar katmanını gidererek düzlük ve paralellik sağlanır; kaba zımpara izlerini gidererek uygun parlaklığa ulaşılır; uzun ömür, yüksek yüzey parlaklığı, iyi stabilite.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Beş eksenli taşlama tezgahı için reçine taşlama diski",
      "summary": "Reçine bağlayıcı ile, elmas veya CBN aşırı sert aşıntı malzemesi ile donatılmıştır, beş eksenli taşlama tezgahının yüksek hassasiyetli hareketine uyum sağlar, sert metal, yüksek hızlı çelik gibi zor işlenen malzemelerin karmaşık yüzeylerinin hassas taşlanması için özellikle kullanılır ve CNC takım imalatının çekirdek sarf malzemesidir.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Sertleştirilmiş karbit çelik bağlayıcılı",
      "summary": "Kesici aletler ve zorlu aşınma parçaları için tasarlanmıştır — tavlama durumunda doğrudan tornalama, frezeleme ve delme işlemi yapılabilir, dövme ve kaynak desteği sağlar, özel ekipman olmadan şekillendirme tamamlanabilir; sertleştirme sonrası HRC 60–70, aşınma direnci yüksek kobalt içeriğine sahip sertleştirilmiş karbite yakındır, tokluk sıradan sertleştirilmiş karbitten çok daha üstündür, tam yaşam döngüsü maliyeti konvansiyonel alaşımlı kalıp çeliğinden çok daha düşüktür.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "ar": [
    {
      "id": "strong-grooving-wheels",
      "name": "قرص قطع الأخدود عالي القوة",
      "summary": "يجمع قرص قطع الأخدود عالي القوة SAP بين مزايا الأقراص المعدنية والسيراميكية، ويتميز بذاتية حدة عالية، وحده عالية، والحفاظ على الشكل العالي، وسهولة الصقل، وهو مناسب بشكل خاص لمعالجة عالية الكفاءة لأدوات القطع الدوارة والشفرات من الكربيد الفولاذ السريع والسيرميت.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "قرص صقل خلفية شريحة LED أشباه الموصلات",
      "summary": "يُستخدم في الصقل الدقيق لمواد أشباه الموصلات فائقة الصلابة مثل الأزركون والسيليكون كربيد (SiC)، مثل صقل خلفية ركيزة LED من الأزركون، ركيزة SiC، ركيزة GaAs، وما إلى ذلك؛ جيد في التجديد الذاتي، عالي في الحفاظ على الشكل، سهل في الإصلاح، معدل خدوش منخفض، معدل كسر منخفض.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "فولاذ عالي السرعة من المساحيق",
      "summary": "يُستخدم فولاذ عالي السرعة من المساحيق من سلسلة SAP بشكل رئيسي في صناعة القوالب والقطع الأداوات عالية الجودة، ويستبدل المواد المستوردة؛ ويمكن تهيئة قطع معقدة عبر التشكيل شبه النهائي، مع محتوى منخفض للشوائب، ويتضمن عدة سلاسل مثل فولاذ القوالب، الفولاذ السريع المقاوم للصدأ عالي الكروم، الفولاذ السريع للنحاس والنيكل، وغير ذلك.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "لوح انتشار حراري من سبائك TiNiCo فائقة",
      "summary": "تُستخدم في قوالب الانحناء الحراري لزجاج ثلاثي الأبعاد وإدارة الحرارة في أشباه الموصلات، مع تسخين متجانس ودرجة استواء عالية وعمر طويل، وتدعم الأحجام المخصصة غير القياسية.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "عجلة ترقيم رقائق SiC",
      "summary": "قرص ماس برابطة سيراميك معدني متجانسة وأحادية (مركب معدني بيني)؛ طحن خشن 2000# بتقدم كبير وكفاءة عالية، وتلميع نهائي 30000# بسطح أقل من 2nm، مما يقلل بشكل كبير كمية التصليح اللاحق ويزيد نسبة الإنتاج الجيد.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "قرص الماس لصقل وتقطيع الزوايا لألواح السيليكون الكهروضوئية",
      "summary": "إزالة آثار المنشار وطبقة损伤 السطحية بعد التقطيع المربع، تحقيق المسطحية والتوازي؛ إزالة آثار الصقل الخشن تحقيقا للنعومة المقابلة؛ عمر افتراضي طويل، نعومة سطحية عالية، ثبات جيد.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "قرص ماس راتنجي لطحن بخمسة محاور",
      "summary": "مع رابط راتنجي، مدمج مع شدة فائقة الصلابة من الماس أو CBN، مناسب لحركة عالية الدقة لطحن بخمسة محاور، متخصص لطحن دقيق للأسطح المعقدة لمواد يصعب تشكيلها مثل الكربيد والفولاذ عالي السرعة، وهو المستهلك الأساسي لصناعة أدوات CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "الكربيد المسبوك الرابطة الفولاذية",
      "summary": "موجهة نحو أدوات القطع ومكونات التآكل الشديدة — في حالة التلدين يمكن المعالجة مباشرةً بالتقطيع والتشطيب بالفرز والخزق، تدعم الصب والليامة، ويمكن التشكيل دون معدات خاصة؛ بعد التصلب HRC 60–70، ومقاومة التآكل تقترب من الكربيد المسبوك عالي الكوبالت، والليونة تتفوق بكثير على الكربيد المسبوك العادي، وتكلفة دورة الحياة الكاملة أقل بكثير من فولاذ القوالب السبائكي الاعتيادي.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ],
  "vi": [
    {
      "id": "strong-grooving-wheels",
      "name": "Đĩa mài rãnh chịu lực cao",
      "summary": "Đĩa mài rãnh chịu lực cao SAP kết hợp các lợi thế của đĩa mài kim loại và đĩa gốm, có độ tự sắc cao, độ sắc bén cao, khả năng giữ hình dạng cao và dễ chỉnh sửa, đặc biệt thích hợp cho gia công hiệu suất cao các dụng cụ cắt thân quay và dao của carbide cứng, thép tốc độ cao luyện bột và kim loại gốm.",
      "image": "/assets/img/diamond-wheels.webp"
    },
    {
      "id": "led-backgrinding-wheels",
      "name": "Đĩa mài mỏng lưng chip LED bán dẫn",
      "summary": "Được ứng dụng trong việc mài chính xác các vật liệu bán dẫn cực cứng như sapphire, SiC, ví dụ như mài mỏng lưng đế sapphire LED, đế SiC, đế GaAs; khả năng tự mài sắc tốt, độ giữ hình dạng cao, dễ chỉnh sửa, tỷ lệ xước thấp, tỷ lệ vỡ thấp.",
      "image": "/assets/img/wafer-backgrind.webp"
    },
    {
      "id": "pm-high-speed-steel",
      "name": "thép tốc độ cao luyện bột",
      "summary": "Thép tốc độ cao luyện bột của dòng SAP chủ yếu được sử dụng trong ngành công nghiệp khuôn và dụng cụ cao cấp, thay thế vật liệu nhập khẩu; có thể chế tạo chi tiết phức tạp bằng phương pháp định hình gần đạt, hàm lượng tạp chất thấp và bao gồm nhiều dòng như thép khuôn, thép không gỉ tốc độ cao crom cao, thép tốc độ cao titan và niken, cùng nhiều dòng khác.",
      "image": "/assets/img/pm-steel.webp"
    },
    {
      "id": "tinico-heat-spreader",
      "name": "Tấm tản nhiệt hợp kim siêu TiNiCo",
      "summary": "Dùng trong khuôn ép nhiệt kính 3D và quản lý nhiệt bán dẫn, làm nóng đều, độ phẳng cao, tuổi thọ dài, hỗ trợ kích thước tùy chỉnh phi tiêu chuẩn.",
      "image": "/assets/img/tinico.webp"
    },
    {
      "id": "sic-wafer-wheels",
      "name": "Đĩa mài mỏng wafer SiC",
      "summary": "Đĩa mài kim cương với chất kết dính gốm kim loại đồng nhất đơn lẻ (hợp chất liên kim); mài thô 2000# hiệu quả cao với chạy dao lớn, mài tinh 30000# độ nhẵn 2nm trở xuống, giảm đáng kể lượng đánh bóng công đoạn sau, nâng cao tỷ lệ đạt.",
      "image": "/assets/img/sic-wafer.webp"
    },
    {
      "id": "pv-ingot-wheels",
      "name": "Đĩa mài kim cương để vát góc và mài vuông thanh silic quang điện",
      "summary": "Loại bỏ vết cưa và lớp bề mặt bị tổn thương sau khi cắt vuông, đạt được độ phẳng và song song; loại bỏ vết mài thô, đạt được độ bóng tương ứng; tuổi thọ dài, độ bóng bề mặt cao, tính ổn định tốt.",
      "image": "/assets/img/pv-ingot.webp"
    },
    {
      "id": "resin-wheels",
      "name": "Đĩa mài nhựa kết dính cho máy mài 5 trục",
      "summary": "Sử dụng nhựa làm chất kết dính, kết hợp với hạt mài siêu cứng kim cương hoặc CBN, phù hợp với chuyển động chính xác cao của máy mài 5 trục, chuyên dụng cho việc mài chính xác bề mặt phức tạp của các vật liệu khó gia công như carbide cứng, thép tốc độ cao, là vật liệu tiêu hao cốt lõi trong sản xuất dao cụ CNC.",
      "image": "/assets/img/resin-wheels.webp"
    },
    {
      "id": "steel-bonded-carbide",
      "name": "Carbide cứng liên kết thép",
      "summary": "Hướng đến dụng cụ cắt và chi tiết chịu mài mòn khắc nghiệt — ở trạng thái ủ có thể gia công trực tiếp tiện, phay, khoan, hỗ trợ rèn và hàn, hình thành không cần thiết bị đặc biệt; sau tôi cứng HRC 60–70, khả năng chống mài mòn gần bằng carbide cứng hàm lượng coban cao, độ dai vượt xa carbide cứng thông thường, chi phí vòng đời toàn bộ thấp hơn nhiều so với thép khuôn hợp kim thông thường.",
      "image": "/assets/img/steel-bonded-carbide.webp"
    }
  ]
};
