# -*- coding: utf-8 -*-
"""One-off deep content patch:
1. Re-derive truncated news descriptions (sentence-boundary, no ellipsis).
2. Product detail imgs: width/height + eager + fetchpriority (LCP image).
3. News hero imgs: width/height + eager + fetchpriority.
4. Insert localized <h2> before <ul class="specs"> on product pages.
"""
import os
import re
import json
import glob
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_news_pages import make_desc as news_make_desc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIMS = json.load(open(os.path.join(ROOT, "_data", "imageDims.js"),
                       encoding="utf-8")) if False else None

# imageDims.js is a JS file; re-measure quickly instead.
from PIL import Image  # noqa: E402

DIMS = {}
for f in os.listdir(os.path.join(ROOT, "assets", "img")):
    p = os.path.join(ROOT, "assets", "img", f)
    try:
        with Image.open(p) as im:
            DIMS["/assets/img/" + f] = (im.width, im.height)
    except Exception:
        pass

SPECS_WORD = {
    "en": "Specifications", "zh": "技术参数", "zh-tw": "技術參數",
    "de": "Technische Daten", "ja": "仕様", "ko": "사양",
    "ru": "Технические характеристики", "es": "Especificaciones",
    "pt": "Especificações", "fr": "Caractéristiques",
    "it": "Specifiche", "tr": "Teknik Özellikler",
    "ar": "المواصفات", "vi": "Thông số kỹ thuật",
}

MARKER_P = "<!-- GENERATED by gen_product_pages.py -->"
MARKER_N = "GENERATED by gen_news_pages.py"


def first_paragraph(html):
    m = re.search(r"<p>(.*?)</p>", html, re.DOTALL)
    if not m:
        return ""
    txt = re.sub(r"<[^>]+>", "", m.group(1))
    return txt.replace("\n", " ").strip()


def patch_img(tag):
    """Add width/height; make eager+fetchpriority for hero/product images."""
    m = re.search(r'src="([^"]+)"', tag)
    if not m:
        return tag, False
    src = m.group(1)
    if src not in DIMS:
        return tag, False
    w, h = DIMS[src]
    changed = False
    out = tag
    if "width=" not in out:
        out = out.replace('src="%s"' % src,
                          'src="%s" width="%d" height="%d"' % (src, w, h), 1)
        changed = True
    # hero/product-top images: lazy loading delays the LCP
    if 'loading="lazy"' in out:
        out = out.replace('loading="lazy"',
                          'loading="eager" fetchpriority="high"', 1)
        changed = True
    return out, changed


stats = {"news_desc": 0, "news_img": 0, "prod_img": 0, "h2": 0, "skipped": 0}

# --- 1+3: news detail pages ---
for f in sorted(glob.glob(os.path.join(ROOT, "*", "news", "*.md"))):
    md = open(f, encoding="utf-8").read()
    if MARKER_N not in md:
        stats["skipped"] += 1
        continue
    fm = re.match(r"^(---\n.*?\n---\n)", md, re.DOTALL)
    if not fm:
        stats["skipped"] += 1
        continue
    head, body = fm.group(1), md[fm.end():]
    lang_m = re.search(r"^lang:\s*(\S+)", head, re.MULTILINE)
    lang = lang_m.group(1) if lang_m else "en"

    # description re-derivation
    para = first_paragraph(body)
    if para:
        new_desc = news_make_desc({"body": para, "title": ""}, limit=150)
        m = re.search(r'^description: ("(?:[^"\\]|\\.)*")\s*$', head,
                      re.MULTILINE)
        if m:
            old = json.loads(m.group(1))
            if old != new_desc:
                head = (head[:m.start(1)]
                        + json.dumps(new_desc, ensure_ascii=False)
                        + head[m.end(1):])
                stats["news_desc"] += 1

    # hero images
    def _img_sub(m):
        new, chg = patch_img(m.group(0))
        if chg:
            stats["news_img"] += 1
        return new
    body = re.sub(r"<img[^>]*>", _img_sub, body)
    open(f, "w", encoding="utf-8", newline="\n").write(head + body)

# --- 2+4: product detail pages ---
for f in sorted(glob.glob(os.path.join(ROOT, "*", "products", "*.md"))):
    md = open(f, encoding="utf-8").read()
    if MARKER_P not in md:
        stats["skipped"] += 1
        continue
    fm = re.match(r"^(---\n.*?\n---\n)", md, re.DOTALL)
    if not fm:
        stats["skipped"] += 1
        continue
    head, body = fm.group(1), md[fm.end():]
    lang_m = re.search(r"^lang:\s*(\S+)", head, re.MULTILINE)
    lang = lang_m.group(1) if lang_m else "en"

    def _img_sub(m):
        new, chg = patch_img(m.group(0))
        if chg:
            stats["prod_img"] += 1
        return new
    body = re.sub(r"<img[^>]*>", _img_sub, body)

    if ('<ul class="specs">' in body
            and not re.search(r"<h2>[^<]*</h2>\s*<ul", body)):
        word = SPECS_WORD.get(lang, SPECS_WORD["en"])
        body = body.replace('<ul class="specs">',
                            "<h2>%s</h2>\n      <ul class=\"specs\">" % word, 1)
        stats["h2"] += 1

    open(f, "w", encoding="utf-8", newline="\n").write(head + body)

print(stats)
