# -*- coding: utf-8 -*-
"""End-to-end test of the publish page's file format.

Generates news articles exactly the way admin/publish.html does, drops them into
the content folders, builds the site and checks that the new article (a) gets its
own page and (b) shows up in that language's /<lang>/news/ index. Afterwards the
test files are removed and the build is restored.
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SLUG = "zz-e2e-test-article"
DATE = "2026-10-03"
NODE = r"C:\Users\cll\.workbuddy\binaries\node\versions\22.22.2-5\node.exe"

SAMPLES = {
    "en": {
        "title": "E2E test article for the multilingual publish page",
        "description": "Temporary article used to verify that a CMS-created article appears in the listing.",
        "section": "Company News",
        "body": "This paragraph was generated by the end-to-end test.\n\nA second paragraph so the body has more than one block.",
    },
    "zh": {
        "title": "端到端测试文章（多语言一键发布验证）",
        "description": "用于验证通过后台新增的新闻会自动出现在新闻列表中。",
        "section": "公司新闻",
        "body": "第一段正文，由端到端测试生成。\n\n第二段正文。",
    },
}


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)


def text_to_html(t):
    s = t.strip()
    return "\n".join("<p>" + p.replace("\n", "<br>") + "</p>" for p in s.split("\n\n"))


def build(lang, data):
    desc = data["description"]
    if lang in ("zh", "zh-tw") and not desc.startswith("*发布日期"):
        label = "发布日期" if lang == "zh" else "發布日期"
        desc = "*" + label + "：" + DATE + "* " + desc
    fm = "\n".join([
        "---",
        "layout: news-detail.njk",
        "lang: " + lang,
        "permalink: /%s/news/%s/" % (lang, SLUG),
        "title: " + yaml_str(data["title"]),
        "description: " + yaml_str(desc),
        "pageType: news",
        "newsSlug: " + SLUG,
        'newsDate: "%s"' % DATE,
        "newsSection: " + yaml_str(data["section"]),
        "---",
        "",
    ])
    return fm + text_to_html(data["body"]) + "\n"


def main():
    created = []
    for lang, data in SAMPLES.items():
        p = os.path.join(ROOT, lang, "news", SLUG + ".md")
        with open(p, "w", encoding="utf-8") as f:
            f.write(build(lang, data))
        created.append(p)
    print("created %d test articles" % len(created))

    print("--- sample generated file (%s) ---" % SAMPLES and os.path.relpath(created[1], ROOT))
    print(open(created[1], encoding="utf-8").read())

    r = subprocess.run(["npm", "run", "build"], cwd=ROOT, capture_output=True, text=True,
                       shell=True)
    print("build exit:", r.returncode)
    tail = [l for l in (r.stdout or "").splitlines() if "Wrote" in l or "Error" in l]
    print("build:", tail[-1] if tail else "(no summary)")

    ok = True
    for lang in SAMPLES:
        detail = os.path.join(ROOT, "_site", lang, "news", SLUG, "index.html")
        idx = os.path.join(ROOT, "_site", lang, "news", "index.html")
        has_detail = os.path.exists(detail)
        html = open(idx, encoding="utf-8").read() if os.path.exists(idx) else ""
        in_list = ("/news/%s/" % SLUG) in html
        cards = html.count("news-card-title")
        print("%s: detail page=%s | listed=%s | cards on index=%d" % (lang, has_detail, in_list, cards))
        if not (has_detail and in_list):
            ok = False

    for p in created:
        os.remove(p)
    d = os.path.join(ROOT, "_site")
    import shutil
    for lang in SAMPLES:
        shutil.rmtree(os.path.join(d, lang, "news", SLUG), ignore_errors=True)
    subprocess.run(["npm", "run", "build"], cwd=ROOT, capture_output=True, text=True, shell=True)
    print("test articles removed and site rebuilt")
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
