# -*- coding: utf-8 -*-
"""Extend admin/config.yml so every visible text block is editable in the CMS:

1. products-<lang>: new `summary` field (首頁/列表卡片的简介 — now stored in the
   product page's own front matter, i.e. one source of truth per language).
2. pages-<lang>: add privacy.md + search.md entries (they existed on disk but
   had no CMS entry).
3. New collections:
   - ui-strings  -> data/i18n.json   (首页/按钮/搜索页 UI 文案)
   - site-info   -> data/site.json   (品牌、联系方式、导航、页脚、多语言品牌串)
All new YAML is generated, then validated by scripts/_validate_cms_config.py.

admin/config.yml is built by running these, IN THIS ORDER:
    1. scripts/_extend_cms_config.py        summary / privacy+search / ui-strings / site-info
    2. scripts/_reorder_cms_collections.py  Chinese collections first + per-collection description
    3. scripts/_harden_cms_fields.py        ASCII slug templates + pinned permalinks
    4. scripts/_validate_cms_config.py      must report 0 errors
"""
import json
import os
import re

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

LANGS = ["en", "zh", "zh-tw", "de", "ja", "ko", "ru", "es", "pt", "fr", "it",
         "tr", "ar", "vi"]

i18n = json.load(open("data/i18n.json", encoding="utf-8"))
site = json.load(open("data/site.json", encoding="utf-8"))

# friendly field labels for the UI-string keys
UI_LABELS = {
    "view": "按钮：查看产品",
    "quote": "按钮：获取报价",
    "core": "板块标题：核心产品",
    "learn": "链接：了解更多",
    "why": "板块标题：为什么选择我们",
    "project": "文案：有项目要谈",
    "ai": "按钮：AI 在线咨询",
    "why1": "优势 1",
    "why2": "优势 2",
    "why3": "优势 3",
    "why4": "优势 4",
    "search_title": "搜索页标题",
    "search_ph": "搜索框提示文字",
    "search_go": "搜索按钮",
    "search_found": "结果数量文字（如：条结果）",
    "search_none": "无结果文字",
}
FOOTER_LABELS = {
    "inquiry": "小标题：实时询价",
    "rfq": "链接：提交询价",
    "quickLinks": "小标题：快捷链接",
    "rights": "版权行",
    "aiBtn": "按钮：AI 咨询",
    "chatPanel": "聊天窗标题",
    "chatInput": "聊天输入框提示",
    "chatSend": "聊天发送按钮",
    "chatWelcome": "聊天欢迎语",
    "privacy": "隐私政策链接文字",
}
BRAND_LABELS = {
    "suffix": "标题后缀（<title>）",
    "desc": "默认 SEO 描述",
    "title": "首页标题",
}
NAV_LABELS = {
    "key": "标识（不要改）",
    "label": "英文标签",
    "zhLabel": "中文标签",
    "zhTwLabel": "繁体标签",
    "labels": "其它语言标签",
}

src = open("admin/config.yml", encoding="utf-8").read()


def block_range(name):
    """Return (start, end) char offsets of a top-level collection block."""
    m = re.search(r'^  - name: "%s"\n' % re.escape(name), src, re.MULTILINE)
    if not m:
        return None
    start = m.start()
    nxt = re.compile(r'^  - name: "', re.MULTILINE).search(src, m.end())
    return start, (nxt.start() if nxt else len(src))


# ---------------------------------------------------------------- 1. summary field
SUMMARY_HINT = {
    "zh": "首页与产品列表卡片上的简介文字（1-2 句）。",
    "zh-tw": "首頁與產品列表卡片上的簡介文字（1-2 句）。",
}
def end_of_flow_map(text, start):
    """Given an offset at a line that begins a YAML flow mapping ('- {'),
    return the offset just after the line where brace depth returns to 0."""
    depth = 0
    i = start
    started = False
    while i < len(text):
        ch = text[i]
        if ch == "{":
            depth += 1
            started = True
        elif ch == "}":
            depth -= 1
            if started and depth == 0:
                nl = text.find("\n", i)
                return (nl + 1) if nl != -1 else len(text)
        i += 1
    return len(text)


count_summary = 0
for lang in LANGS:
    rng = block_range("products-" + lang)
    assert rng, "products-%s not found" % lang
    start, end = rng
    block = src[start:end]
    m = re.search(r'^(\s*)- \{ label: "[^"]*", name: "description", widget: "text"',
                  block, re.MULTILINE)
    assert m, "description field not found in products-" + lang
    indent = m.group(1)
    insert_at = end_of_flow_map(block, m.start())
    label = "卡片简介" if lang.startswith("zh") else "Card summary"
    hint = SUMMARY_HINT.get(lang, "Short summary shown on the home & products cards (1-2 sentences).")
    line = '%s- { label: "%s", name: "summary", widget: "text", hint: "%s" }\n' % (
        indent, label, hint)
    new_block = block[:insert_at] + line + block[insert_at:]
    src = src[:start] + new_block + src[end:]
    count_summary += 1
print("summary fields added:", count_summary)

# ------------------------------------------------- 2. privacy + search page entries
FIELD_RE = re.compile(
    r'(^        fields:\n)((?:^          - .*\n(?:^              .*\n)*)+)',
    re.MULTILINE)
count_pages = 0
for lang in LANGS:
    rng = block_range("pages-" + lang)
    if not rng:
        # Only en/zh/zh-tw have hand-maintained page collections; the other
        # languages are generated by the zh->all auto-translation pipeline,
        # so they intentionally have no "pages" menu.
        print("  (skip pages-%s: collection not defined)" % lang)
        continue
    start, end = rng
    block = src[start:end]
    m = re.search(r'^      - name: news-%s\n' % re.escape(lang), block, re.MULTILINE)
    assert m, "news page entry not found in pages-" + lang
    tail = re.search(r'^      - name: ', block[m.end():], re.MULTILINE)
    insert_at = m.end() + (tail.start() if tail else len(block) - m.end())
    span = FIELD_RE.search(block, m.end())
    assert span, "field template not found in pages-" + lang
    fields_tpl = span.group(1) + span.group(2)

    privacy_label = (site["footerPerLang"].get(lang) or site["footerPerLang"]["en"])["privacy"]
    search_label = (i18n.get(lang) or i18n["en"])["search_title"]
    added = (
        "      - name: privacy-%s\n"
        '        label: "%s (页面)"\n'
        '        file: "%s/privacy.md"\n' % (lang, privacy_label, lang)
        + fields_tpl +
        "      - name: search-%s\n"
        '        label: "%s（搜索页）"\n'
        '        file: "%s/search.md"\n' % (lang, search_label, lang)
        + fields_tpl
    )
    block = block[:insert_at] + added + block[insert_at:]
    src = src[:start] + block + src[end:]
    count_pages += 1
print("privacy+search entries added for languages:", count_pages)

# ------------------------------------------------------- 3. new collections YAML
NL = "\n"


def obj_field(name, label, sub_fields, indent):
    pad = " " * indent
    out = pad + '- { label: "%s", name: "%s", widget: "object", collapsed: true,\n' % (label, name)
    out += pad + "    fields: [\n"
    for fname, flabel in sub_fields:
        out += pad + '      { label: "%s", name: "%s", widget: "string" },\n' % (flabel, fname)
    out = out.rstrip(",\n") + ",\n"
    out += pad + "    ] }\n"
    return out


ui = ["  - name: \"ui-strings\"\n",
      "    label: \"界面文案 · UI Strings（中文为源，其它语言自动翻译）\"\n",
      "    description: \"首页板块标题、按钮、搜索页等界面文字。改中文即可，翻译由自动同步完成。\"\n",
      "    files:\n",
      "      - name: ui-strings\n",
      "        label: \"界面文案（14 语言）\"\n",
      "        file: \"data/i18n.json\"\n",
      "        fields:\n"]
for lang in LANGS:
    strings = i18n.get(lang) or i18n["en"]
    sub = [(k, UI_LABELS.get(k, k)) for k in strings.keys()]
    ui.append(obj_field(lang, "%s（%s）" % (lang, (site["langs"][LANGS.index(lang)]["native"])), sub, 10))

site_c = ["  - name: \"site-info\"\n",
          "    label: \"站点信息 · Site Info\"\n",
          "    description: \"品牌、联系方式、社交链接、导航与页脚文案。中文栏位为源，其它语言由自动同步翻译。\"\n",
          "    files:\n",
          "      - name: site-info\n",
          "        label: \"站点信息\"\n",
          "        file: \"data/site.json\"\n",
          "        fields:\n"]
simple = [
    ("name", "公司全称（英文）", "string"), ("nameZh", "公司全称（中文）", "string"),
    ("nameZhTw", "公司全称（繁体）", "string"), ("shortName", "品牌简称", "string"),
    ("domain", "域名（用于 canonical/hreflang）", "string"),
    ("logo", "Logo", "image"), ("brochure", "产品手册 PDF", "file"),
    ("email", "邮箱", "string"), ("phone", "电话", "string"),
    ("wechat", "微信", "string"), ("whatsapp", "WhatsApp 号码（含国家码，不带 +）", "string"),
    ("address", "地址（英文）", "string"), ("addressZh", "地址（中文）", "string"),
    ("addressZhTw", "地址（繁体）", "string"),
    ("linkedin", "LinkedIn", "string"), ("youtube", "YouTube", "string"),
    ("tawkPropertyId", "在线客服 ID（Tawk.to）", "string"),
    ("web3formsKey", "询价表单密钥（Web3Forms）", "string"),
]
for name, label, widget in simple:
    site_c.append('          - { label: "%s", name: "%s", widget: "%s", required: false }\n'
                  % (label, name, widget))

site_c.append('          - { label: "默认语言", name: "defaultLang", widget: "string", required: false }\n')
site_c.append('          - { label: "回退语言", name: "fallbackLang", widget: "string", required: false }\n')
site_c.append('          - { label: "AI 接口路径", name: "aiChatPath", widget: "string", required: false }\n')

# brandPerLang / footerPerLang: block-style object fields, one per language.
# NOTE: a flow mapping ({...}) may not contain a block sequence, so the outer
# field uses block style while the per-language entries stay flow style.
site_c.append('          - label: "多语言品牌与标题"\n'
              '            name: "brandPerLang"\n'
              '            widget: "object"\n'
              '            collapsed: true\n'
              '            fields:\n')
for lang in LANGS:
    obj = site["brandPerLang"].get(lang) or site["brandPerLang"]["en"]
    native = [l["native"] for l in site["langs"] if l["code"] == lang][0]
    sub = [(k, BRAND_LABELS.get(k, k)) for k in obj.keys()]
    site_c.append(obj_field(lang, "%s · %s" % (lang, native), sub, 14))

site_c.append('          - label: "页脚与聊天窗文案"\n'
              '            name: "footerPerLang"\n'
              '            widget: "object"\n'
              '            collapsed: true\n'
              '            fields:\n')
for lang in LANGS:
    obj = site["footerPerLang"].get(lang) or site["footerPerLang"]["en"]
    native = [l["native"] for l in site["langs"] if l["code"] == lang][0]
    sub = [(k, FOOTER_LABELS.get(k, k)) for k in obj.keys()]
    site_c.append(obj_field(lang, "%s · %s" % (lang, native), sub, 14))

site_c.append('          - label: "导航菜单"\n'
              '            name: "nav"\n'
              '            widget: "list"\n'
              '            collapsed: true\n'
              '            fields:\n'
              '              - { label: "标识（勿改）", name: "key", widget: "string" }\n'
              '              - { label: "英文标签", name: "label", widget: "string" }\n'
              '              - { label: "中文标签", name: "zhLabel", widget: "string" }\n'
              '              - { label: "繁体标签", name: "zhTwLabel", widget: "string" }\n'
              '              - { label: "URL · en", name: "en", widget: "string" }\n'
              '              - { label: "URL · zh", name: "zh", widget: "string" }\n'
              '              - { label: "URL · zh-tw", name: "zh-tw", widget: "string" }\n'
              '              - { label: "其它语言标签", name: "labels", widget: "object", collapsed: true,\n'
              '                  fields: [\n')
blk = []
for code, native in [(l["code"], l["native"]) for l in site["langs"]
                     if l["code"] not in ("en", "zh", "zh-tw")]:
    blk.append('                    { label: "%s", name: "%s", widget: "string" },' % (native, code))
site_c.append("\n".join(blk).rstrip(",") + "\n")
site_c.append("                  ] }\n")

src = src.rstrip("\n") + "\n\n" + "".join(ui) + "\n" + "".join(site_c)
open("admin/config.yml", "w", encoding="utf-8", newline="\n").write(src)

# ---------------------------------------------------------------- validate
cfg = yaml.safe_load(src)
print("collections now:", len(cfg["collections"]))
print("last two:", [c["name"] for c in cfg["collections"][-2:]])
