# -*- coding: utf-8 -*-
"""In-place augment the 112 generated product detail pages with per-product,
per-language keyword lists (from _data/productKeywords.json).

Idempotent: it only rewrites pages that carry the GENERATED marker and only
when the keywords content actually differs, so hand-edited files are never
touched.

Usage: python scripts/augment_product_keywords.py
"""
import os, re, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "<!-- GENERATED by gen_product_pages.py -->"

with open(os.path.join(ROOT, "_data", "productKeywords.json"), encoding="utf-8") as f:
    KWS = json.load(f)


def parse_fm(md):
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", md, re.DOTALL)
    if not m:
        return None, None, md
    fm, rest = m.group(1), m.group(2)
    return fm, rest, None


def set_kw(fm, key, value_lines):
    lines = fm.split("\n")
    # drop any existing `keywords:` block (lines until a non-indented key)
    out = []
    skipping = False
    for ln in lines:
        if ln.startswith("keywords:"):
            skipping = True
            continue
        if skipping and (ln.startswith(" ") or ln == ""):
            continue
        skipping = False
        out.append(ln)
    # insert before the last key's block end; just append to end of fm
    out.extend(value_lines)
    return "\n".join(out)


def main():
    changed = 0
    for prod_md in sorted(__import__("glob").glob(os.path.join(ROOT, "*", "products", "*.md"))):
        with open(prod_md, encoding="utf-8") as f:
            md = f.read()
        if MARKER not in md:
            continue
        fm, rest, whole = parse_fm(md)
        if fm is None:
            continue
        lang_m = re.search(r"^lang:\s*(\S+)", fm, re.M)
        pid_m = re.search(r"^productId:\s*(\S+)", fm, re.M)
        if not lang_m or not pid_m:
            continue
        lang, pid = lang_m.group(1), pid_m.group(1)
        kws = (KWS.get(pid) or {}).get(lang) or []
        if not kws:
            continue
        # build yaml list
        val_lines = ["keywords: " + json.dumps(kws, ensure_ascii=False)]
        new_fm = set_kw(fm, "keywords", val_lines)
        new_md = "---\n" + new_fm + "\n---\n" + (rest or "")
        if new_md != md:
            with open(prod_md, "w", encoding="utf-8") as fo:
                fo.write(new_md)
            changed += 1
    print("augmented %d detail pages with product keywords." % changed)


if __name__ == "__main__":
    main()
