# -*- coding: utf-8 -*-
"""Generate per-product detail pages for all 14 languages.

Reads each <lang>/products.md, extracts every product-block by its id, and
writes <lang>/products/<slug>.md with the product-detail.njk layout plus a
localized title / description and the rich product content (image + specs +
CTA already present in the source block).

Slugs come from _data/productSlugs.json (single source of truth shared with
seo.js + the templates). Idempotent: it only deletes files that carry the
GENERATED marker, so nothing hand-written is ever touched.

Usage: python scripts/gen_product_pages.py
"""
import os, re, json, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

with open(os.path.join(ROOT, "_data", "productSlugs.json"), encoding="utf-8") as f:
    SLUGS = json.load(f)

MARKER = "<!-- GENERATED by gen_product_pages.py -->"


def extract_blocks(md):
    """Return list of (pid, inner_html) for each product-block in the md."""
    blocks = []
    marker = '<div class="product-block" id="'
    parts = md.split(marker)
    for chunk in parts[1:]:
        first, rest = chunk.split("\n", 1)
        pid = first[: first.find('"')]
        rest = rest.rstrip()
        # drop the outer product-block closing </div></div>
        rest = re.sub(r"</div>\s*</div>\s*$", "", rest)
        # drop ONLY the first <h2> (the product name — the detail page
        # renders its own <h1>). Section headings like
        # <h2>Specifications</h2> in the block body are content and must
        # survive regeneration.
        rest = re.sub(r"<h2>[^<]*</h2>\s*", "", rest, count=1)
        blocks.append((pid, rest))
    return blocks


def first_paragraph(html):
    m = re.search(r"<p>(.*?)</p>", html, re.DOTALL)
    if not m:
        return ""
    txt = re.sub(r"<[^>]+>", "", m.group(1))
    return txt.replace("\n", " ").strip()


# Sentence-ending punctuation, Latin + CJK. Used to cut descriptions at a
# real sentence/clause boundary instead of mid-word followed by "…" — a
# truncated fragment makes Google rewrite the snippet and looks broken in
# Product schema.
_SENT_END = ".!?。！？"
_CLAUSE_END = ";,，、；"

def make_desc(txt, limit=155):
    if len(txt) <= limit:
        return txt
    cut = txt[:limit]
    # 1) Prefer the last full-sentence end inside the limit.
    sp = max(cut.rfind(ch) for ch in _SENT_END)
    if sp >= int(limit * 0.4):
        return cut[: sp + 1].rstrip()
    # 2) Otherwise extend just past the limit to the next sentence end
    #    rather than cutting the sentence in half.
    m = re.search(r"[.!?。]", txt[limit : limit + 80])
    if m:
        return txt[: limit + m.end()].strip()
    # 3) Otherwise the last clause boundary (comma/semicolon) inside the limit.
    sp = max(cut.rfind(ch) for ch in _CLAUSE_END)
    if sp >= int(limit * 0.5):
        return cut[: sp + 1].rstrip()
    # 4) Degenerate single long sentence: word-boundary cut when possible,
    #    otherwise hard cut; strip dangling punctuation either way. No "…" —
    #    a clean fragment beats a broken one.
    sp = cut.rfind(" ")
    if sp > int(limit * 0.6):
        cut = cut[:sp]
    return cut.rstrip(" \t" + _SENT_END + _CLAUSE_END + "-–—")


def yaml_str(s):
    # a JSON string is valid double-quoted YAML; escapes quotes/backslashes
    return json.dumps(s, ensure_ascii=False)


def generate():
    count = 0
    for prod_md in sorted(glob.glob(os.path.join(ROOT, "*", "products.md"))):
        lang = os.path.basename(os.path.dirname(prod_md))
        with open(prod_md, encoding="utf-8") as f:
            md = f.read()
        fm = re.search(r"^---\n(.*?)\n---", md, re.DOTALL)
        lang_fm = lang
        if fm:
            m = re.search(r"^lang:\s*(\S+)", fm.group(1), re.MULTILINE)
            if m:
                lang_fm = m.group(1)
        out_dir = os.path.join(os.path.dirname(prod_md), "products")
        os.makedirs(out_dir, exist_ok=True)
        # clean previously generated detail files only
        for old in glob.glob(os.path.join(out_dir, "*.md")):
            try:
                with open(old, encoding="utf-8") as fo:
                    if MARKER in fo.read(400):
                        os.remove(old)
            except Exception:
                pass
        for pid, inner in extract_blocks(md):
            slug = SLUGS.get(pid)
            if not slug:
                print("WARN: no slug for %s in %s" % (pid, lang_fm))
                continue
            name_m = re.search(r'<img class="pb-img"[^>]*alt="([^"]*)"', inner)
            name = name_m.group(1) if name_m else pid
            img_m = re.search(r'<img class="pb-img"[^>]*src="([^"]*)"', inner)
            img = img_m.group(1) if img_m else "/assets/img/logo.png"
            desc = make_desc(first_paragraph(inner))
            # Close BOTH the inner content <div> and the outer .product-block
            # <div>. A single closer left the outer block unclosed: product
            # detail pages still rendered (the browser closes the div when the
            # parent ends), but the products index stacks eight of these
            # blocks, so every block after the first nested inside the
            # previous one and the layout collapsed.
            body = '<div class="product-block">\n' + inner + "\n</div>\n</div>"
            # Fix any CTA that points at another language's contact page
            # (e.g. a stale /en/contact/) to THIS language's own contact page.
            # Single replacement — safe to run after fix_cta_links.py too.
            body = body.replace('href="/en/contact/"', 'href="/%s/contact/"' % lang_fm)
            out = []
            out.append("---")
            out.append("layout: product-detail.njk")
            out.append("lang: " + lang_fm)
            out.append("permalink: /%s/products/%s/" % (lang_fm, slug))
            out.append("title: " + yaml_str(name))
            out.append("description: " + yaml_str(desc))
            out.append("pageType: product")
            out.append("productId: " + pid)
            out.append("productImage: " + img)
            out.append("---")
            out.append(MARKER)
            out.append("")
            out.append(body)
            with open(os.path.join(out_dir, slug + ".md"), "w", encoding="utf-8") as fo:
                fo.write("\n".join(out) + "\n")
            count += 1
    print("Generated %d product detail pages." % count)


if __name__ == "__main__":
    generate()
