# -*- coding: utf-8 -*-
"""Regenerate _data/products.js from the product pages' front matter.

Why: the home-page cards and the products list used to read product names and
summaries from _data/products.js while the product pages lived in
<lang>/products/<slug>.md — two places to edit the same text. The md files are
now the single source (title / summary / productImage), and this script
projects them into the shape the templates and seo.js already consume:

    { "<lang>": [ { id, name, summary, image }, ... ] }

Order comes from _data/productOrder.json.

Run after editing product pages:  python scripts/gen_products_data.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

LANGS = ["en", "zh", "zh-tw", "de", "ja", "ko", "ru", "es", "pt", "fr", "it",
         "tr", "ar", "vi"]

order = json.load(open("_data/productOrder.json", encoding="utf-8"))
slugs = json.load(open("_data/productSlugs.json", encoding="utf-8"))


def read_front_matter(path):
    if not os.path.exists(path):
        return {}
    md = open(path, encoding="utf-8").read()
    m = re.match(r"^---\r?\n(.*?)\r?\n---", md, re.DOTALL)
    if not m:
        return {}
    fm = {}
    for key in ("title", "summary", "productImage"):
        mm = re.search(r'^%s:\s*(.+)$' % key, m.group(1), re.MULTILINE)
        if mm:
            raw = mm.group(1).strip()
            if raw.startswith('"'):
                try:
                    fm[key] = json.loads(raw)
                except ValueError:
                    fm[key] = raw.strip('"')
            else:
                fm[key] = raw
    return fm


data = {}
missing = []
for lang in LANGS:
    rows = []
    for pid in order:
        slug = slugs.get(pid)
        fm = read_front_matter(os.path.join(lang, "products", (slug or "") + ".md"))
        if not fm.get("title"):
            missing.append("%s/%s" % (lang, slug))
            continue
        rows.append({
            "id": pid,
            "name": fm.get("title", pid),
            "summary": fm.get("summary", ""),
            "image": fm.get("productImage", "/assets/img/logo.png"),
        })
    data[lang] = rows

if missing:
    print("WARNING: missing product pages:", ", ".join(missing[:8]),
          "(%d total)" % len(missing))

header = (
    "// GENERATED by scripts/gen_products_data.py — do not edit by hand.\n"
    "// Source of truth: <lang>/products/<slug>.md front matter\n"
    "// (title / summary / productImage) + _data/productOrder.json for order.\n"
    "module.exports = "
)
body = json.dumps(data, ensure_ascii=False, indent=2)
open("_data/products.js", "w", encoding="utf-8", newline="\n").write(header + body + ";\n")
print("wrote _data/products.js — %d languages x %d products" % (len(data), len(order)))
