# -*- coding: utf-8 -*-
"""Generate per-article news detail pages + rewrite the listing page into a
card grid, for EVERY language that carries a hand-written news body.

The 21 news articles are the SAME across all 14 languages (only translated),
so each article gets ONE stable slug shared by every language (mirroring the
product pages). Slugs come from _data/newsSlugs.json in canonical order; the
article at position i in any language maps to CANONICAL_SLUGS[i].

For each not-yet-generated <lang>/news.md we:
  1. Split the body into articles (### title + *date* + prose, under ## section).
  2. Assign each its canonical slug by position.
  3. Emit <lang>/news/<slug>.md (news-detail.njk) and a GENERATED card-grid
     listing that links to the detail pages.
  4. Record the localized title into newsSlugs.json so the sitemap can label
     every language's detail URL.

Idempotent: languages whose news.md already carries the GENERATED marker are
skipped (en/zh were generated in an earlier pass); only files carrying the
marker are rewritten/removed.

Usage: python scripts/gen_news_pages.py
"""
import os, re, json, glob, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "<!-- GENERATED by gen_news_pages.py -->"

# Languages that still have the original ### -based news.md (to be generated).
# en/zh were done in an earlier pass and now carry the GENERATED marker, so they
# are excluded here AND protected by the marker guard below.
NEW_LANGS = ["zh-tw", "de", "ja", "ko", "ru", "es", "pt", "fr", "it", "tr", "ar", "vi"]


def load_slugs():
    with open(os.path.join(ROOT, "_data", "newsSlugs.json"), encoding="utf-8") as f:
        return json.load(f)


def parse_articles(md):
    """Return list of (section, title, date, body_html, image) in document order."""
    body = re.sub(r"^---\n.*?\n---\n?", "", md, count=1, flags=re.DOTALL)
    lines = body.split("\n")
    arts, section = [], "News"
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("## "):
            section = ln[3:].strip()
            i += 1
            continue
        if ln.startswith("### "):
            title = ln[4:].strip()
            date, buf, image = "", [], None
            i += 1
            # Optional *...* date line (any language; must contain an ISO date).
            if i < len(lines):
                s = lines[i].strip()
                if s.startswith("*") and s.endswith("*") and re.search(r"\d{4}-\d{2}-\d{2}", s):
                    m = re.search(r"\d{4}-\d{2}-\d{2}", s)
                    date = m.group(0)
                    i += 1
            # collect until next heading
            while i < len(lines) and not lines[i].startswith("## ") and not lines[i].startswith("### "):
                b = lines[i].strip()
                if b:
                    im = re.match(r"!\[([^\]]*)\]\(([^)]+)\)", b)
                    if im:
                        image = im.group(2)
                    else:
                        buf.append(b)
                i += 1
            arts.append({"section": section, "title": title, "date": date,
                         "body": " ".join(buf).strip(), "image": image})
            continue
        i += 1
    return arts


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)


def make_desc(art, limit=150):
    t = art["body"]
    if not t:
        return art["title"]
    if len(t) <= limit:
        return t
    cut = t[:limit]
    sp = cut.rfind(" ")
    if sp > limit * 0.6:
        cut = cut[:sp]
    return cut.rstrip() + "…"


def gen_listing(art_rows, lang, title, desc):
    out = []
    out.append("---")
    out.append("layout: page.njk")
    out.append("lang: " + lang)
    out.append("permalink: /" + lang + "/news/")
    out.append("title: " + yaml_str(title))
    out.append("description: " + yaml_str(desc))
    out.append("pageType: news")
    out.append("---")
    out.append(MARKER)
    out.append("")
    # group by section, preserving first-seen order
    groups, last = [], None
    for slug, art in art_rows:
        sec = art["section"]
        if sec != last:
            groups.append([sec, []])
            last = sec
        groups[-1][1].append((slug, art))
    out.append('<div class="news-group">')
    for sec_label, items in groups:
        out.append('  <h2>%s</h2>' % html.escape(sec_label))
        out.append('  <div class="news-grid">')
        for slug, art in items:
            d = art.get("date") or ""
            t = art["title"]
            out.append('    <article class="news-card">')
            if art.get("image"):
                out.append('      <img class="news-card-img" src="%s" alt="%s" loading="lazy" />' % (art["image"], html.escape(t)))
            out.append('      <h3 class="news-card-title"><a href="/%s/news/%s/">%s</a></h3>' % (lang, slug, html.escape(t)))
            if d:
                out.append('      <p class="news-card-date">%s</p>' % html.escape(d))
            out.append('      <p class="news-card-desc">%s</p>' % html.escape(make_desc(art)))
            out.append('    </article>')
        out.append('  </div>')
    out.append('</div>')
    return "\n".join(out) + "\n"


def main():
    news_slugs = load_slugs()
    canonical = list(news_slugs.keys())
    print("Canonical slugs (%d): %s" % (len(canonical), ", ".join(canonical)))
    total = 0
    for lang in NEW_LANGS:
        path = os.path.join(ROOT, lang, "news.md")
        if not os.path.exists(path):
            print("  skip (no file):", lang)
            continue
        with open(path, encoding="utf-8") as f:
            md = f.read()
        if MARKER in md:
            print("  skip (already generated):", lang)
            continue
        fm = re.match(r"^---\n(.*?)\n---\n?", md, re.DOTALL)
        fmlines = fm.group(1).split("\n") if fm else []
        page_title = page_desc = ""
        for fl in fmlines:
            mm = re.match(r'^title:\s*"?(.*?)"?\s*$', fl)
            if mm:
                page_title = mm.group(1)
            dm = re.match(r'^description:\s*"?(.*?)"?\s*$', fl)
            if dm:
                page_desc = dm.group(1)

        arts = parse_articles(md)
        if len(arts) != len(canonical):
            print("  WARNING %s: %d articles vs %d canonical slugs — verify ordering!" % (lang, len(arts), len(canonical)))
        out_dir = os.path.join(ROOT, lang, "news")
        os.makedirs(out_dir, exist_ok=True)
        # remove previously generated
        for old in glob.glob(os.path.join(out_dir, "*.md")):
            try:
                if MARKER in open(old, encoding="utf-8").read(400):
                    os.remove(old)
            except Exception:
                pass
        rows = []
        for idx, a in enumerate(arts):
            a["section"] = a["section"].strip()
            slug = canonical[idx] if idx < len(canonical) else None
            if not slug:
                slug = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", a["title"].lower()).strip("-")
            a["slug"] = slug
            rows.append((slug, a))
            image = a.get("image")
            dp = []
            dp.append("---")
            dp.append("layout: news-detail.njk")
            dp.append("lang: " + lang)
            dp.append("permalink: /%s/news/%s/" % (lang, slug))
            dp.append("title: " + yaml_str(a["title"]))
            dp.append("description: " + yaml_str(make_desc(a)))
            dp.append("pageType: news")
            dp.append("newsSlug: " + slug)
            dp.append("newsSection: " + yaml_str(a["section"]))
            if a.get("date"):
                dp.append("newsDate: " + yaml_str(a["date"]))
            if image:
                dp.append("newsImage: " + yaml_str(image))
            dp.append("---")
            dp.append(MARKER)
            dp.append("")
            if image:
                dp.append('<img class="news-hero-img" src="%s" alt="%s" loading="lazy" />' % (image, html.escape(a["title"])))
                dp.append("")
            body = html.unescape(a["body"].strip())
            if body:
                dp.append("<p>" + body + "</p>")
            with open(os.path.join(out_dir, slug + ".md"), "w", encoding="utf-8") as fo:
                fo.write("\n".join(dp) + "\n")
            total += 1
            # record localized title (single source of truth for the sitemap)
            news_slugs.setdefault(slug, {})[lang] = a["title"]
        # rewrite listing
        new_listing = gen_listing(rows, lang, page_title, page_desc)
        with open(path, "w", encoding="utf-8") as fo:
            fo.write(new_listing)
        print("  %s: %d detail pages + listing rewritten" % (lang, len(rows)))
    # write back newsSlugs.json with all languages represented
    with open(os.path.join(ROOT, "_data", "newsSlugs.json"), "w", encoding="utf-8") as f:
        json.dump(news_slugs, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("Generated %d news detail pages; newsSlugs.json now covers %d languages." % (total, len(NEW_LANGS) + 2))


if __name__ == "__main__":
    main()
