# -*- coding: utf-8 -*-
"""Generate per-article news detail pages + rewrite the listing page into a
card grid, for the languages that carry a hand-written news body (en, zh for
now; the other 11 share the English body and can be added later).

For each <lang>/news.md we:
  1. Split the body into articles: each is a `### <title>` heading followed by
     a `*Date: ...*` line and the article paragraphs, grouped under a `## <section>`.
  2. Match every article to a slug from _data/newsSlugs.json (by its exact title).
  3. Emit <lang>/news/<slug>.md (layout news-detail.njk, localized title/desc/
     date/image) and a GENERATED-marker listing that keeps each section as a
     card grid linking to the detail pages (all content stays on the detail
     page, so the listing stays light and every article gets its own URL).

Idempotent: only files carrying the GENERATED marker are rewritten/removed.

Usage: python scripts/gen_news_pages.py
"""
import os, re, json, glob, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "<!-- GENERATED by gen_news_pages.py -->"
LANGS = ["en", "zh"]


def load_slugs():
    with open(os.path.join(ROOT, "_data", "newsSlugs.json"), encoding="utf-8") as f:
        raw = json.load(f)
    by_en, by_zh = {}, {}
    for slug, m in raw.items():
        by_en[m["en"]] = slug
        by_zh[m["zh"]] = slug
    return {"en": by_en, "zh": by_zh}


def parse_articles(md):
    """Return list of (section, title, date, body_html, image)."""
    # drop front matter
    body = re.sub(r"^---\n.*?\n---\n?", "", md, count=1, flags=re.DOTALL)
    # drop the de-duped marker comment line
    lines = body.split("\n")
    arts, section = [], "News"
    i = 0
    cur = None
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("## "):
            section = ln[3:].strip()
            i += 1
            continue
        if ln.startswith("### "):
            title = ln[4:].strip()
            date, buf, image = "", [], None
            i += 1
            # optional date line
            if i < len(lines) and lines[i].strip().startswith("*Date"):
                m = re.search(r"(\d{4}-\d{2}-\d{2})", lines[i])
                date = m.group(1) if m else lines[i].strip().strip("* ")
                i += 1
            # collect until next heading
            while i < len(lines) and not lines[i].startswith("## ") and not lines[i].startswith("### "):
                b = lines[i].strip()
                if b:
                    im = re.match(r"!\[([^\]]*)\]\(([^)]+)\)", b)
                    if im:
                        image = im.group(2)
                    else:
                        buf.append(b)
                i += 1
            cur = {"section": section, "title": title, "date": date,
                   "body": " ".join(buf).strip(), "image": image}
            arts.append(cur)
            continue
        i += 1
    return arts


def slug_of(title, lang, maps):
    m = maps[lang]
    if title in m:
        return m[title]
    # fallback: normalize
    t = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", title.lower()).strip("-")
    return t


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)


def clean_date(zh_date):
    return zh_date


def make_desc(art, limit=150):
    t = art["body"]
    if not t:
        return art["title"]
    if len(t) <= limit:
        return t
    cut = t[:limit]
    sp = cut.rfind(" ")
    if sp > limit * 0.6:
        cut = cut[:sp]
    return cut.rstrip() + "…"


def gen_listing(art_rows, lang, title, desc):
    """art_rows: list of (slug, art) where art has .title/.date/.body/.image/.section."""
    out = []
    out.append("---")
    out.append("layout: page.njk")
    out.append("lang: " + lang)
    out.append("permalink: /" + lang + "/news/")
    out.append("title: " + yaml_str(title))
    out.append("description: " + yaml_str(desc))
    out.append("pageType: news")
    out.append("---")
    out.append(MARKER)
    out.append("")
    # group by section, preserving first-seen order
    groups, last = [], None
    for slug, art in art_rows:
        sec = art["section"]
        if sec != last:
            groups.append([sec, []])
            last = sec
        groups[-1][1].append((slug, art))
    out.append('<div class="news-group">')
    for sec_label, items in groups:
        out.append('  <h2>%s</h2>' % html.escape(sec_label))
        out.append('  <div class="news-grid">')
        for slug, art in items:
            d = art.get("date") or ""
            t = art["title"]
            out.append('    <article class="news-card">')
            if art.get("image"):
                out.append('      <img class="news-card-img" src="%s" alt="%s" loading="lazy" />' % (art["image"], html.escape(t)))
            out.append('      <h3 class="news-card-title"><a href="/%s/news/%s/">%s</a></h3>' % (lang, slug, html.escape(t)))
            if d:
                out.append('      <p class="news-card-date">%s</p>' % html.escape(d))
            out.append('      <p class="news-card-desc">%s</p>' % html.escape(make_desc(art)))
            out.append('    </article>')
        out.append('  </div>')
    out.append('</div>')
    return "\n".join(out) + "\n"


def main():
    maps = load_slugs()
    total = 0
    for lang in LANGS:
        path = os.path.join(ROOT, lang, "news.md")
        with open(path, encoding="utf-8") as f:
            md = f.read()
        fm = re.match(r"^---\n(.*?)\n---\n?", md, re.DOTALL)
        fmlines = fm.group(1).split("\n")
        page_title = ""
        page_desc = ""
        for fl in fmlines:
            mm = re.match(r'^title:\s*"?(.*?)"?\s*$', fl)
            if mm:
                page_title = mm.group(1)
            dm = re.match(r'^description:\s*"?(.*?)"?\s*$', fl)
            if dm:
                page_desc = dm.group(1)

        arts = parse_articles(md)
        out_dir = os.path.join(ROOT, lang, "news")
        os.makedirs(out_dir, exist_ok=True)
        # remove previously generated
        for old in glob.glob(os.path.join(out_dir, "*.md")):
            try:
                if MARKER in open(old, encoding="utf-8").read(400):
                    os.remove(old)
            except Exception:
                pass
        # section localized label
        sec_label = arts[0]["section"]
        rows = []
        seen = {}
        for a in arts:
            a["section"] = a["section"].strip()
            slug = slug_of(a["title"], lang, maps)
            a["slug"] = slug
            # dedup repeated titles (e.g. TiNiCo appears twice): suffix a counter
            key = a["title"]
            if key in seen:
                seen[key] += 1
                slug = "%s-%d" % (slug, seen[key])
                a["slug"] = slug
            else:
                seen[key] = 0
            rows.append((slug, a))
            # write detail page
            image = a.get("image")
            dp = []
            dp.append("---")
            dp.append("layout: news-detail.njk")
            dp.append("lang: " + lang)
            dp.append("permalink: /%s/news/%s/" % (lang, slug))
            dp.append("title: " + yaml_str(a["title"]))
            dp.append("description: " + yaml_str(make_desc(a)))
            dp.append("pageType: news")
            dp.append("newsSlug: " + slug)
            dp.append("newsSection: " + yaml_str(a["section"]))
            if a.get("date"):
                dp.append("newsDate: " + yaml_str(a["date"]))
            if image:
                dp.append("newsImage: " + yaml_str(image))
            dp.append("---")
            dp.append(MARKER)
            dp.append("")
            if image:
                dp.append('<img class="news-hero-img" src="%s" alt="%s" loading="lazy" />' % (image, html.escape(a["title"])))
                dp.append("")
            dp.append("")
            # body is a single clean paragraph join; emit one <p> (articles are prose blocks)
            body = html.unescape(a["body"].strip())
            if body:
                dp.append("<p>" + body + "</p>")
            with open(os.path.join(out_dir, slug + ".md"), "w", encoding="utf-8") as fo:
                fo.write("\n".join(dp) + "\n")
            total += 1
        # rewrite listing
        new_listing = gen_listing(rows, lang, page_title, page_desc)
        with open(path, "w", encoding="utf-8") as fo:
            fo.write(new_listing)
    print("Generated %d news detail pages + rewritten listings for %s." % (total, ", ".join(LANGS)))


if __name__ == "__main__":
    main()
